import { sampleHawaiiTrip, sampleTrip } from "./sample-trip";
import type { PublishedGuide } from "./guide-types";
import { inferRoutePoints } from "./route-points";
import type { TripInput } from "./trip-types";

function tripInput(overrides: Partial<TripInput>): TripInput {
  return {
    title: "", destination: "", dates: "", travelers: "2 travelers", budget: "", origin: "", notes: "", places: "", mustHaves: "", fixedBookings: "", lockedItems: "", movableItems: "", optionalItems: "",
    transportModes: ["Drive my car", "Fly + rental car"], uncertainty: "Weather and road conditions", decisionDate: "Before nonrefundable booking", constraints: "Verify current access, weather and road conditions", ...overrides,
  };
}

export const featuredPublishedGuides: PublishedGuide[] = [
  {
    id: "leaves-southwest-loop",
    title: "From red rock to neon",
    destination: "American Southwest",
    author: "She Leaves Notes",
    tripDate: "April–May 2026",
    duration: "6 days",
    actualCost: "$2,500 for two",
    summary: "Vegas, Zion, Bryce, Page, Monument Valley and the Grand Canyon in a tight six-day loop—with an honest warning about how much time disappears behind the wheel.",
    story: "This route was driven from the Bay Area and revised repeatedly around The Wave lottery. It worked in six days, but seven gives Monument Valley and Bryce the daylight they deserve.",
    bestFor: "Travelers who want five iconic parks and are willing to make an explicit time-versus-cost choice.",
    highlights: ["Zion and Bryce in one sweep", "Antelope Canyon timed entry", "Monument Valley sunset", "Grand Canyon sunrise"],
    tips: ["Add a seventh day if you can", "Book Antelope Canyon and Monument Valley lodging early", "Do not count a nine-hour drive as a sightseeing day"],
    sourceUrl: "https://leavesnotes.com/posts/southwest-six-day-loop/",
    branch: { ...sampleTrip.branches[1], routePoints: inferRoutePoints("American Southwest Zion Bryce Page The Wave Monument Valley Grand Canyon", "Drive my car", "extra-day") },
    forkInput: sampleTrip.originalInput!,
    publishedAt: "2026-04-30T00:00:00.000Z",
    editorVerified: true,
  },
  {
    id: "leaves-hawaii-big-island",
    title: "Above the volcano, beneath the Milky Way",
    destination: "Hawaii Big Island",
    author: "She Leaves Notes",
    tripDate: "February 2026",
    duration: "7 days",
    actualCost: "$4,000 for two",
    summary: "A Kona–Hilo loop with manta rays, sea turtles, Mauna Kea sunset and a flexible window for Volcanoes National Park.",
    story: "The useful part of this itinerary is not one perfect order. It is keeping both coasts fixed while one evening stays movable for summit weather or volcanic activity.",
    bestFor: "Travelers who want wildlife and volcanic landscapes without rebuilding the whole week when conditions change.",
    highlights: ["Night manta-ray experience", "Volcanoes National Park", "Mauna Kea sunset", "Hilo waterfalls"],
    tips: ["Keep one evening unbooked", "Carry warm layers for the summit", "Use official conditions before changing the route"],
    sourceUrl: "https://leavesnotes.com/posts/hawaii-big-island-week/",
    branch: { ...sampleHawaiiTrip.branches[0], routePoints: inferRoutePoints("Hawaii Big Island Kona Volcano Mauna Kea Hilo Waimea", "Fly + rental car", "weather-first") },
    forkInput: sampleHawaiiTrip.originalInput!,
    publishedAt: "2026-02-23T00:00:00.000Z",
    editorVerified: true,
  },
  {
    id: "leaves-sequoia-kings-canyon",
    title: "Staggering giants",
    destination: "Sequoia & Kings Canyon",
    author: "She Leaves Notes",
    tripDate: "May 2026",
    duration: "2 days · 1 night",
    actualCost: "Not itemized in the post",
    summary: "A compact Bay Area weekend through both parks, built around one structural decision: Kings Canyon first, then let Sequoia deliver the bigger finish.",
    story: "This was a last-minute weekend without an in-park lodge or dawn departure. Kings Canyon worked as the quiet scenic opening; General Sherman, Big Trees Trail and Moro Rock escalated Day 2 instead of making the first park feel like an afterthought.",
    bestFor: "Bay Area travelers who want both parks in one weekend and are comfortable with a long drive home.",
    highlights: ["Kings Canyon Scenic Byway", "Zumwalt Meadow", "Big Trees Trail", "Moro Rock summit"],
    tips: ["Visit Kings Canyon before Sequoia", "Carry a printed park map because signal disappears", "Use Moro Rock as the payoff, ideally before the parking fills"],
    sourceUrl: "https://leavesnotes.com/posts/sequoia-kings-canyon-weekend/",
    branch: {
      id: "kings-first", name: "Kings Canyon → Sequoia", subtitle: "The two-park weekend in the right order", days: 2, cost: 650, transportMode: "Drive my car", transitHours: 13, driveHours: 13, luggageFlexibility: "High", bookingComplexity: "Low", fatigue: 8, experienceScore: 9, flexibility: "Medium", summary: "Use Kings Canyon as the scenic opening and Sequoia as the dramatic finish.",
      changes: ["Keep one cabin night between the parks", "Save the giant sequoias and summit for Day 2"], tradeoffs: ["A long drive home", "No deep hikes", "Only one night"],
      timeline: [
        { day: "Day 1", title: "Bay Area → Kings Canyon", detail: "Fresno lunch, General Grant, scenic drive, waterfalls and Zumwalt Meadow" },
        { day: "Night 1", title: "Cabin between the parks", detail: "Avoid the harder descent into Three Rivers" },
        { day: "Day 2", title: "Sequoia → Bay Area", detail: "General Sherman, Big Trees Trail, Tunnel Log and Moro Rock" },
      ],
      routePoints: [
        { label: "San Francisco", lat: 37.7749, lng: -122.4194 }, { label: "Fresno", lat: 36.7378, lng: -119.7871 }, { label: "General Grant", lat: 36.7469, lng: -118.9717 }, { label: "Zumwalt Meadow", lat: 36.794, lng: -118.598 }, { label: "General Sherman", lat: 36.581, lng: -118.751 }, { label: "Moro Rock", lat: 36.544, lng: -118.765 }, { label: "San Francisco", lat: 37.7749, lng: -122.4194 },
      ],
    },
    forkInput: tripInput({ title: "Sequoia and Kings Canyon weekend", destination: "Sequoia & Kings Canyon", dates: "2 days · 1 night", budget: "$650 estimate", origin: "San Francisco Bay Area", notes: "Day 1 drive from the Bay Area to Kings Canyon for General Grant, the scenic drive, waterfalls and Zumwalt Meadow. Sleep between the parks. Day 2 visit General Sherman, Big Trees Trail, Tunnel Log and Moro Rock, then drive home.", places: "Fresno, General Grant Tree, Zumwalt Meadow, General Sherman Tree, Big Trees Trail, Tunnel Log, Moro Rock", mustHaves: "Kings Canyon first; Big Trees Trail; Moro Rock", fixedBookings: "One cabin night between the parks", lockedItems: "Two-day weekend", movableItems: "Moro Rock timing", optionalItems: "Parker Group and roadside stops", uncertainty: "Park access, weather and Moro Rock parking", constraints: "No second hotel night; return to the Bay Area on Day 2" }),
    publishedAt: "2026-05-16T00:00:00.000Z", editorVerified: true,
  },
  {
    id: "leaves-kilauea-eruption-timing",
    title: "Watching the tilt, waiting on Pele",
    destination: "Kīlauea · Hawaii Big Island",
    author: "She Leaves Notes",
    tripDate: "February 2026",
    duration: "7-day flexible window",
    actualCost: "Higher-odds timing costs a last-minute premium",
    summary: "A field-tested way to improve the odds of seeing a Kīlauea eruption: use the USGS forecast, tilt trend, live crater feed and a real buffer on both sides of the predicted window.",
    story: "The trip bracketed a USGS window with two buffer days on either side and caught Episode 42 one day after the forecast. It is a decision strategy, not a guarantee: enjoy the island normally until tilt and sustained fountaining justify the drive.",
    bestFor: "Big Island travelers willing to keep lodging and one evening flexible for a rare live event.",
    highlights: ["USGS forecast window", "Real-time tilt trend", "Crater livestream", "Devastation Trail viewing"],
    tips: ["Book only when the forecast narrows to roughly 4–7 days", "Keep at least two buffer days on each side", "Do not drive in for occasional splashes; wait for sustained fountaining"],
    sourceUrl: "https://leavesnotes.com/posts/kilauea-eruption-timing/",
    branch: {
      id: "eruption-window", name: "Forecast-window strategy", subtitle: "Keep the island trip fixed and move one live-event night", days: 7, cost: 4200, transportMode: "Fly + rental car", transitHours: 18, driveHours: 18, luggageFlexibility: "Medium", bookingComplexity: "High", fatigue: 7, experienceScore: 10, flexibility: "High", summary: "Bracket the likely episode with buffer days and activate the park drive only when the live signals align.",
      changes: ["Book around a narrowed forecast", "Leave one evening movable", "Use Devastation Trail only after official signals strengthen"], tradeoffs: ["Last-minute booking premium", "No guaranteed eruption", "Possible nighttime drive"],
      timeline: [
        { day: "Before booking", title: "Wait for a narrow forecast", detail: "Last episode about a week ago, stable tilt and a 4–7 day USGS window" },
        { day: "Days 1–4", title: "Stay on vacation", detail: "Kona, Mauna Kea and Hilo while checking official data once or twice daily" },
        { day: "Signal 1", title: "Watch, don’t drive", detail: "Occasional splashes mean close, not started" },
        { day: "Signal 2", title: "Activate the branch", detail: "Sustained fountains, increasing height and rapidly dropping tilt" },
        { day: "Viewing", title: "Devastation Trail", detail: "Follow official access guidance; D point had the best view during this episode" },
      ],
      routePoints: [{ label: "Kona", lat: 19.64, lng: -155.997 }, { label: "Mauna Kea", lat: 19.759, lng: -155.4567 }, { label: "Hilo", lat: 19.7074, lng: -155.0885 }, { label: "Devastation Trail", lat: 19.4095, lng: -155.263 }, { label: "Kona", lat: 19.64, lng: -155.997 }],
    },
    forkInput: tripInput({ title: "Big Island eruption-window trip", destination: "Hawaii Big Island", dates: "7 days around the predicted eruption window", budget: "$4,200 estimate", origin: "Kona airport", notes: "Keep a normal Kona–Hilo island loop, but bracket the predicted Kīlauea eruption window with two buffer days before and after. Leave one evening movable for Devastation Trail if official signals align.", places: "Kona, Mauna Kea, Hilo, Volcanoes National Park, Devastation Trail", mustHaves: "A complete Big Island trip even if no eruption happens", fixedBookings: "Arrival and departure flights", lockedItems: "Use only official USGS and park access information", movableItems: "One evening and one Hilo activity", optionalItems: "Second volcano visit", uncertainty: "Kīlauea eruption timing", decisionDate: "Check forecast and tilt daily", constraints: "No guarantee of viewing; avoid unsafe or closed areas" }),
    publishedAt: "2026-02-13T00:00:00.000Z", editorVerified: true,
  },
  {
    id: "leaves-eastern-canada-loop",
    title: "Too-green leaves, deer at the door",
    destination: "Eastern Canada",
    author: "She Leaves Notes",
    tripDate: "October 2025",
    duration: "6 days",
    actualCost: "CAD $4,662 for two",
    summary: "Montreal, Quebec City and Mont Tremblant framed around the part that justified the trip: a panoramic deer chalet inside Parc Omega.",
    story: "Early October was too early for peak color in Montreal, Tremblant was pleasant rather than transcendent, and the cities worked as one-day stops. The deer cabin—with park admission, hot tub, wood stove and animals at the door—became the reason to build the whole route.",
    bestFor: "Travelers who want a low-hiking fall loop and are willing to make one special accommodation the centerpiece.",
    highlights: ["Montreal walking loop", "Quebec City Old Town", "Mont Tremblant gondola", "Parc Omega panoramic chalet"],
    tips: ["Aim for mid-to-late October for stronger city color", "Stay inside Tremblant village", "If budget is tight, cut Tremblant before cutting Parc Omega"],
    sourceUrl: "https://leavesnotes.com/posts/eastern-canada-fall-loop/",
    branch: {
      id: "deer-cabin-loop", name: "Cities around the deer cabin", subtitle: "Make Parc Omega the anchor, not an add-on", days: 6, cost: 4662, transportMode: "Fly + rental car", transitHours: 18, driveHours: 11, luggageFlexibility: "Medium", bookingComplexity: "High", fatigue: 6, experienceScore: 8, flexibility: "Medium", summary: "Use Montreal without a car, then pick up a rental for Quebec City, Tremblant and Parc Omega.",
      changes: ["Delay the rental car until leaving Montreal", "Reserve the Parc Omega chalet first", "Keep both cities to one focused day"], tradeoffs: ["CAD $4,662 total", "Several hotel changes", "Foliage timing risk"],
      timeline: [
        { day: "Day 1", title: "Vancouver → Montreal", detail: "Late arrival and sleep" }, { day: "Day 2", title: "Montreal without a car", detail: "Old Port, Saint Joseph’s, Beaver Lake, Mont Royal and Notre-Dame" }, { day: "Day 3", title: "Montreal → Quebec City", detail: "Pick up the rental and walk Old Town" }, { day: "Day 4", title: "Quebec City → Mont Tremblant", detail: "Resort village and sunset" }, { day: "Day 5", title: "Tremblant → Parc Omega", detail: "Morning gondola, then panoramic deer chalet" }, { day: "Day 6", title: "Parc Omega → Montreal", detail: "Safari loop and evening flight" },
      ],
      routePoints: [{ label: "Montreal", lat: 45.5019, lng: -73.5674 }, { label: "Quebec City", lat: 46.8139, lng: -71.208 }, { label: "Mont Tremblant", lat: 46.209, lng: -74.585 }, { label: "Parc Omega", lat: 45.682, lng: -74.903 }, { label: "Montreal", lat: 45.5019, lng: -73.5674 }],
    },
    forkInput: tripInput({ title: "Eastern Canada fall loop", destination: "Quebec, Canada", dates: "6 days in mid-to-late October", budget: "CAD $4,700 for two", origin: "Montreal airport", notes: "Arrive Montreal, spend one day walking the city, then rent a car for Quebec City, Mont Tremblant and a final panoramic chalet night at Parc Omega before flying home from Montreal.", places: "Montreal, Quebec City, Mont Tremblant, Parc Omega", mustHaves: "Parc Omega panoramic chalet and one Montreal walking day", fixedBookings: "Parc Omega chalet and return flight", lockedItems: "Six-day window", movableItems: "Tremblant night and Quebec City timing", optionalItems: "Extra Tremblant activities", uncertainty: "Fall color timing", constraints: "Keep city stops to one day each" }),
    publishedAt: "2025-10-01T00:00:00.000Z", editorVerified: true,
  },
  {
    id: "leaves-yukon-tombstone",
    title: "Your own Tombstone moment",
    destination: "Yukon",
    author: "She Leaves Notes",
    tripDate: "August–September 2025",
    duration: "5–6 days",
    actualCost: "About CAD $2,800 solo",
    summary: "Whitehorse to Dawson and Tombstone, ordered deliberately from hike to highway to helicopter so every day raises the bar.",
    story: "The iconic first lookout works for a short hike, the Top of the World Highway opens the landscape, and a helicopter landing near Talus Lake unlocks the backcountry for travelers who are not doing a multi-day trek.",
    bestFor: "Travelers who want a remote northern road trip and will budget for one unforgettable helicopter experience.",
    highlights: ["Grizzly Lake first lookout", "Midnight Dome sunset", "Top of the World Highway", "Tombstone helicopter landing"],
    tips: ["Order the trip hike → drive → helicopter", "Confirm the rental allows the Dempster Highway", "Use ground clearance and patience; a 4×4 is not the only workable choice"],
    sourceUrl: "https://leavesnotes.com/posts/yukon-tombstone-five-day-loop/",
    branch: {
      id: "tombstone-escalation", name: "Hike → highway → helicopter", subtitle: "A five-day route that keeps getting bigger", days: 6, cost: 2800, transportMode: "Fly + rental car", transitHours: 27, driveHours: 21, luggageFlexibility: "Medium", bookingComplexity: "High", fatigue: 8, experienceScore: 10, flexibility: "Medium", summary: "Base in Dawson, see Tombstone from the trail, road and air, then close with an aurora attempt in Whitehorse.",
      changes: ["Fly into Whitehorse for rental-car availability", "Keep the clear-weather activities movable", "Budget for the helicopter from the start"], tradeoffs: ["Long Whitehorse–Dawson drives", "Weather dependence", "Expensive helicopter add-on"],
      timeline: [
        { day: "Days 1–2", title: "Whitehorse → Dawson", detail: "Rental car and six-hour drive; split with Whitehorse if needed" }, { day: "Day 3", title: "Tombstone first lookout", detail: "Short Grizzly Lake Trail version, then Midnight Dome sunset" }, { day: "Day 4", title: "Top of the World Highway", detail: "Dawson to Little Gold and back" }, { day: "Day 5", title: "Helicopter → Whitehorse", detail: "Land near Talus Lake, drive south, chase the aurora" }, { day: "Day 6", title: "Whitehorse → Vancouver", detail: "Fly home" },
      ],
      routePoints: [{ label: "Whitehorse", lat: 60.7212, lng: -135.0568 }, { label: "Dawson City", lat: 64.0601, lng: -139.432 }, { label: "Tombstone", lat: 64.487, lng: -138.241 }, { label: "Midnight Dome", lat: 64.076, lng: -139.451 }, { label: "Little Gold", lat: 64.139, lng: -141.0 }, { label: "Talus Lake", lat: 64.51, lng: -138.36 }, { label: "Whitehorse", lat: 60.7212, lng: -135.0568 }],
    },
    forkInput: tripInput({ title: "Yukon and Tombstone loop", destination: "Whitehorse, Dawson City and Tombstone", dates: "5–6 days over Labor Day", travelers: "1 traveler", budget: "CAD $2,800", origin: "Whitehorse airport", notes: "Fly to Whitehorse, rent a suitable vehicle and drive to Dawson. Visit Tombstone’s first Grizzly Lake lookout, Midnight Dome, Top of the World Highway and a helicopter landing near Talus Lake, then return to Whitehorse for an aurora attempt.", places: "Whitehorse, Dawson City, Tombstone, Grizzly Lake lookout, Midnight Dome, Top of the World Highway, Talus Lake", mustHaves: "Tombstone lookout, scenic highway and helicopter", fixedBookings: "Rental car, Dawson hotel and helicopter", lockedItems: "Rental must allow the Dempster Highway", movableItems: "Hike and helicopter weather days", optionalItems: "Aurora chase", uncertainty: "Wind, cloud and helicopter conditions", constraints: "No multi-day backcountry hike" }),
    publishedAt: "2025-08-30T00:00:00.000Z", editorVerified: true,
  },
  {
    id: "leaves-toronto-niagara-no-car",
    title: "A walking loop, a boat in the spray",
    destination: "Toronto + Niagara Falls",
    author: "She Leaves Notes",
    tripDate: "July 2025",
    duration: "2 days",
    actualCost: "Not fully itemized in the post",
    summary: "Two days without a rental car: one direct bus day at Niagara Falls and one compact Toronto landmark loop by train and foot.",
    story: "The Niagara boat was the only unqualified must-do. The attraction pass filled the day but also created a stressful sprint; the better version cuts the bottom two attractions. Toronto works as a focused 3–4 hour walk from Union Station.",
    bestFor: "Short-stop visitors staying near Pearson who want the Falls and downtown Toronto without renting a car.",
    highlights: ["Niagara boat tour", "Niagara Power Station", "Toronto waterfront", "St. Lawrence Market"],
    tips: ["Book Flixbus weeks ahead before fares triple", "Use the 9am outbound and 7pm return", "Cut White Water Walk and one lower-ranked attraction to let the day breathe"],
    sourceUrl: "https://leavesnotes.com/posts/toronto-niagara-no-car-loop/",
    branch: {
      id: "no-car-two-day", name: "Niagara + Toronto without a car", subtitle: "Airport hotel, direct bus and one city walk", days: 2, cost: 650, transportMode: "Fly + public transit", transitHours: 7, driveHours: 0, luggageFlexibility: "Low", bookingComplexity: "Medium", fatigue: 7, experienceScore: 8, flexibility: "Medium", summary: "Use Pearson as the base, Flixbus for Niagara and UP Express for a compact Toronto day.",
      changes: ["Skip the rental car", "Reserve the Niagara bus early", "Trim the attractions pass"], tradeoffs: ["Fixed bus times", "More walking", "Toronto Island does not fit"],
      timeline: [{ day: "Day 1", title: "Pearson → Niagara Falls", detail: "9am Flixbus, boat, Power Station and one extra attraction; 7pm return" }, { day: "Day 2", title: "Toronto city walk", detail: "UP Express to Union, CN Tower, waterfront, St. Lawrence Market and downtown loop" }],
      routePoints: [{ label: "Toronto Pearson", lat: 43.6777, lng: -79.6248 }, { label: "Niagara Falls", lat: 43.0896, lng: -79.0849 }, { label: "Toronto Pearson", lat: 43.6777, lng: -79.6248 }, { label: "Union Station", lat: 43.6452, lng: -79.3806 }, { label: "CN Tower", lat: 43.6426, lng: -79.3871 }, { label: "St. Lawrence Market", lat: 43.6487, lng: -79.3715 }, { label: "Toronto Pearson", lat: 43.6777, lng: -79.6248 }],
    },
    forkInput: tripInput({ title: "Toronto and Niagara without a car", destination: "Toronto + Niagara Falls", dates: "2 days", budget: "CAD $650 estimate excluding flights", origin: "Toronto Pearson airport hotel", notes: "Day 1 use the airport shuttle and direct Flixbus for Niagara Falls, prioritizing the boat, Power Station and one additional attraction. Day 2 take UP Express to Union Station for a compact Toronto walking loop.", places: "Niagara Falls, boat tour, Power Station, CN Tower, Harbourfront, St. Lawrence Market, Gooderham Building, Toronto Sign", mustHaves: "Niagara boat tour and St. Lawrence Market", fixedBookings: "9am outbound and 7pm return bus", lockedItems: "No rental car", movableItems: "Niagara attraction slots", optionalItems: "White Water Walk, cable car, Toronto Island", transportModes: ["Fly + public transit", "Train"], uncertainty: "Bus fares and attraction time slots", constraints: "Two days; base near Pearson" }),
    publishedAt: "2025-07-26T00:00:00.000Z", editorVerified: true,
  },
  {
    id: "leaves-yellowstone-vancouver",
    title: "Falling for the planet, again",
    destination: "Yellowstone from Vancouver",
    author: "She Leaves Notes",
    tripDate: "April–May 2025",
    duration: "6 days",
    actualCost: "About CAD $2,500 for two",
    summary: "A shoulder-season Vancouver–Yellowstone drive with three park nights, carefully chosen lodging and a route split between thermal basins, Mammoth and Lamar Valley.",
    story: "Two sunny park days made the early-May gamble pay off. The route worked, but a three-hour border delay and thin-walled Old Faithful Inn room were the fixes for next time; staying inside the park was still the right structural choice.",
    bestFor: "Road trippers who want Yellowstone before peak season and will accept two long transfer days in each direction.",
    highlights: ["Grand Prismatic overlook", "Old Faithful to Morning Glory boardwalk", "Mammoth Hot Springs", "Lamar Valley at sunset"],
    tips: ["Allow several hours for the southbound border", "Book park lodging early on the official site", "Photograph Grand Prismatic around noon and Morning Glory off midday"],
    sourceUrl: "https://leavesnotes.com/posts/yellowstone-vancouver-loop/",
    branch: {
      id: "yellowstone-park-lodges", name: "Vancouver → three Yellowstone bases", subtitle: "Long transfers, short park commutes", days: 6, cost: 2500, transportMode: "Drive my car", transitHours: 36, driveHours: 36, luggageFlexibility: "High", bookingComplexity: "Medium", fatigue: 9, experienceScore: 9, flexibility: "Medium", summary: "Break the continental drive in Spokane and sleep inside or just outside the park for three distinct touring days.",
      changes: ["Stay in West Yellowstone, Old Faithful and Mammoth", "Use Spokane in both directions", "Reserve Lamar Valley for the Mammoth night"], tradeoffs: ["Four long transfer days", "Border-delay risk", "Frequent hotel changes"],
      timeline: [{ day: "Day 1", title: "Vancouver → Spokane", detail: "Seattle supply stop; plan for the border" }, { day: "Day 2", title: "Spokane → West Yellowstone", detail: "Lunch and fuel in Missoula" }, { day: "Day 3", title: "Lower Loop", detail: "Grand Prismatic, Old Faithful and Morning Glory" }, { day: "Day 4", title: "Mammoth + Lamar", detail: "Upper and middle loops; wildlife at sunset" }, { day: "Day 5", title: "North entrance → Spokane", detail: "Seven-hour return transfer" }, { day: "Day 6", title: "Spokane → Vancouver", detail: "Drive home" }],
      routePoints: [{ label: "Vancouver", lat: 49.2827, lng: -123.1207 }, { label: "Seattle", lat: 47.6062, lng: -122.3321 }, { label: "Spokane", lat: 47.6588, lng: -117.426 }, { label: "Missoula", lat: 46.8721, lng: -113.994 }, { label: "West Yellowstone", lat: 44.6621, lng: -111.1041 }, { label: "Old Faithful", lat: 44.46, lng: -110.828 }, { label: "Mammoth", lat: 44.976, lng: -110.701 }, { label: "Lamar Valley", lat: 44.895, lng: -110.224 }, { label: "Spokane", lat: 47.6588, lng: -117.426 }, { label: "Vancouver", lat: 49.2827, lng: -123.1207 }],
    },
    forkInput: tripInput({ title: "Vancouver to Yellowstone loop", destination: "Yellowstone National Park", dates: "6 days in late April or early May", budget: "CAD $2,500 for two", origin: "Vancouver, BC", notes: "Drive Vancouver to Spokane, then through Missoula to West Yellowstone. Spend three days across the Lower Loop, Old Faithful, Mammoth and Lamar Valley, then return through Spokane.", places: "Seattle, Spokane, Missoula, West Yellowstone, Grand Prismatic, Old Faithful, Morning Glory Pool, Mammoth Hot Springs, Lamar Valley", mustHaves: "Grand Prismatic overlook, Morning Glory boardwalk and Lamar Valley", fixedBookings: "In-park lodging", lockedItems: "Six-day road-trip window", movableItems: "Lower and Upper Loop order", optionalItems: "Extra geyser waits and Spokane sightseeing", uncertainty: "Shoulder-season roads, weather and border delay", constraints: "Stay inside the park where possible" }),
    publishedAt: "2025-04-30T00:00:00.000Z", editorVerified: true,
  },
  {
    id: "leaves-cancun-christmas",
    title: "Cloudy days, impossibly blue",
    destination: "Cancún at Christmas",
    author: "She Leaves Notes",
    tripDate: "December 2024",
    duration: "6 days · 5 nights",
    actualCost: "CAD $8,076 for two",
    summary: "An all-inclusive Cancún base with two day tours that transformed the week: a self-drive speedboat snorkel and a full day at Xplor, tested by a non-swimmer afraid of heights.",
    story: "Flights and the Christmas hotel made up roughly 80% of the cost. Once there, the right strategy was to keep the beach days simple and spend on the two experiences that became the trip: Jungle Tour and Xplor.",
    bestFor: "Nervous first-time adventure travelers who want a comfortable hotel base and guided ways into water and heights.",
    highlights: ["Self-drive Jungle Tour speedboat", "Guided snorkel for non-swimmers", "Xplor Toboganxote and ziplines", "Isla Mujeres half-day"],
    tips: ["Book Xplor transfer slots 2–3 days ahead", "At Xplor pick four activities instead of chasing everything", "Travel outside Christmas to cut the two biggest costs"],
    sourceUrl: "https://leavesnotes.com/posts/cancun-christmas-week/",
    branch: {
      id: "cancun-two-tour-base", name: "All-inclusive base + two anchor tours", subtitle: "Keep five days simple and protect the memorable experiences", days: 6, cost: 5500, transportMode: "Fly + public transit", transitHours: 9, driveHours: 0, luggageFlexibility: "Low", bookingComplexity: "Medium", fatigue: 5, experienceScore: 9, flexibility: "Medium", summary: "Use one hotel for the whole trip, then anchor the week around Jungle Tour and Xplor.",
      changes: ["No rental car", "Pre-book two transfer-based tours", "Leave two full recovery days at the hotel"], tradeoffs: ["Christmas pricing", "Limited local exploration", "All-inclusive commitment"],
      timeline: [{ day: "Night 0", title: "Vancouver → Cancún", detail: "Overnight flight" }, { day: "Day 1", title: "Arrival + hotel", detail: "Check in and recover on the beach" }, { day: "Day 2", title: "Jungle Tour", detail: "Self-drive speedboat and guided snorkel" }, { day: "Day 3", title: "Hotel day", detail: "Beach, pool and all-inclusive meals" }, { day: "Day 4", title: "Xplor", detail: "Full-day adventure park with transfer" }, { day: "Day 5", title: "Isla Mujeres", detail: "Half-day ferry and golf cart" }, { day: "Day 6", title: "Fly home", detail: "Early departure" }],
      routePoints: [{ label: "Cancún Airport", lat: 21.0365, lng: -86.8771 }, { label: "Hotel Zone", lat: 21.1138, lng: -86.757 }, { label: "Aquaworld", lat: 21.099, lng: -86.768 }, { label: "Xplor", lat: 20.588, lng: -87.123 }, { label: "Isla Mujeres", lat: 21.232, lng: -86.735 }, { label: "Hotel Zone", lat: 21.1138, lng: -86.757 }, { label: "Cancún Airport", lat: 21.0365, lng: -86.8771 }],
    },
    forkInput: tripInput({ title: "Cancún base with Jungle Tour and Xplor", destination: "Cancún, Mexico", dates: "6 days · 5 nights", budget: "CAD $8,100 at Christmas; less off-season", origin: "Cancún airport", notes: "Use one all-inclusive hotel in the Cancún hotel zone. Protect one day for Aquaworld Jungle Tour, one full day for Xplor, one half-day for Isla Mujeres and two slower beach or pool days.", places: "Cancún hotel zone, Aquaworld, Xplor, Isla Mujeres", mustHaves: "Jungle Tour and Xplor", fixedBookings: "Flights, hotel and Xplor transfer", lockedItems: "One hotel for all five nights", movableItems: "Tour days based on weather", optionalItems: "Isla Mujeres and extra Xplor activities", transportModes: ["Fly + public transit", "Let TripFork suggest"], uncertainty: "Weather and tour availability", constraints: "Non-swimmer; afraid of heights; no rental car" }),
    publishedAt: "2024-12-25T00:00:00.000Z", editorVerified: true,
  },
  {
    id: "leaves-banff-vancouver-loop",
    title: "Snow at Lake Louise, kangaroos in Kelowna",
    destination: "Canadian Rockies",
    author: "She Leaves Notes",
    tripDate: "September–October 2024",
    duration: "7 days",
    actualCost: "About CAD $2,500 for two",
    summary: "A seven-day Vancouver–Banff loop through five overnight towns, with October mountain weather, winter-tire realities and candid hotel lessons built into the route.",
    story: "The drive itself was half the trip. Kelowna delivered the unexpected kangaroo-farm stop, Calgary served a personal appointment, Banff supplied snowy lakes, and Valemount made the long return manageable. The most hyped Revelstoke stay was the one to reconsider.",
    bestFor: "BC road trippers who want the Rockies as a loop and prefer breaking long drives with practical overnight stops.",
    highlights: ["Kelowna kangaroo farm", "Snowy Lake Louise", "Banff and the Rockies", "Valemount scenic overnight"],
    tips: ["Use 3-peak-snowflake tires for real October conditions", "Download large offline map areas", "Pick transit hotels on value and layout, not hype"],
    sourceUrl: "https://leavesnotes.com/posts/banff-vancouver-loop/",
    branch: {
      id: "banff-five-town-loop", name: "Vancouver → Banff → Valemount", subtitle: "Seven days, five overnight towns", days: 7, cost: 2500, transportMode: "Drive my car", transitHours: 27, driveHours: 27, luggageFlexibility: "High", bookingComplexity: "Medium", fatigue: 8, experienceScore: 8, flexibility: "High", summary: "Break the Rockies loop into Kelowna, Revelstoke, Calgary, Banff and Valemount instead of repeating the same highway.",
      changes: ["Use different outbound and return corridors", "Keep Banff non-negotiable", "Use Valemount to split the drive home"], tradeoffs: ["Five hotel changes", "October snow risk", "Limited time in each town"],
      timeline: [{ day: "Night 1", title: "Vancouver → Kelowna", detail: "Kangaroo farm and practical downtown hotel" }, { day: "Night 2", title: "Kelowna → Revelstoke", detail: "Transit night" }, { day: "Nights 3–4", title: "Revelstoke → Calgary", detail: "Two-night personal stop" }, { day: "Night 5", title: "Calgary → Banff", detail: "Rockies, Lake Louise and mountain weather" }, { day: "Night 6", title: "Banff → Valemount", detail: "Scenic return corridor" }, { day: "Day 7", title: "Valemount → Vancouver", detail: "About seven hours home" }],
      routePoints: [{ label: "Vancouver", lat: 49.2827, lng: -123.1207 }, { label: "Kelowna", lat: 49.888, lng: -119.496 }, { label: "Revelstoke", lat: 50.999, lng: -118.195 }, { label: "Calgary", lat: 51.0447, lng: -114.0719 }, { label: "Banff", lat: 51.1784, lng: -115.5708 }, { label: "Valemount", lat: 52.831, lng: -119.265 }, { label: "Vancouver", lat: 49.2827, lng: -123.1207 }],
    },
    forkInput: tripInput({ title: "Vancouver to Banff loop", destination: "Canadian Rockies", dates: "7 days in late September or early October", budget: "CAD $2,500 for two", origin: "Vancouver, BC", notes: "Drive from Vancouver to Kelowna, Revelstoke, Calgary and Banff, then return through Valemount. Use overnight towns to break the long road days and keep Banff as the non-negotiable centerpiece.", places: "Kelowna, Revelstoke, Calgary, Banff, Lake Louise, Valemount", mustHaves: "Banff, Lake Louise and Kelowna kangaroo farm", fixedBookings: "Banff hotel and any personal Calgary appointment", lockedItems: "Seven-day loop from Vancouver", movableItems: "Revelstoke and Calgary nights", optionalItems: "Extra Revelstoke stop", uncertainty: "October snow and highway conditions", constraints: "Winter-rated tires; download offline maps" }),
    publishedAt: "2024-09-29T00:00:00.000Z", editorVerified: true,
  },
];

export function findFeaturedGuide(id: string) {
  return featuredPublishedGuides.find((guide) => guide.id === id);
}
