import type { TripDocument } from "./trip-types";

export const sampleTrip: TripDocument = {
  id: "sample-southwest-loop",
  title: "What if we win The Wave?",
  destination: "Southwest loop",
  dateSummary: "Apr 30–May 5",
  travelers: "2 travelers",
  budget: "$2,500",
  sourceNotes: "Bay Area road trip through Zion, Bryce, Page, Monument Valley and Grand Canyon. The Wave permit may change the route.",
  inputSummary: {
    origin: "San Francisco Bay Area",
    existingPlan: "Drive from the Bay Area to Las Vegas, then loop through Zion, Bryce, Page, Monument Valley and Grand Canyon before driving home.",
    places: "Las Vegas, Zion, Bryce, Page, The Wave, Antelope Canyon, Monument Valley, Grand Canyon",
    lockedItems: "Six-day window; Antelope Canyon tour; return home by Sunday night",
    movableItems: "Page hotel; Monument Valley day; Grand Canyon sunrise",
    optionalItems: "Lake Powell; Las Vegas evening",
    transportModes: ["Drive my car", "Fly + rental car"],
  },
  decision: {
    name: "The Wave lottery",
    question: "Did we win The Wave permit?",
    decisionDate: "Jul 18",
    status: "pending",
    positiveLabel: "Won",
    negativeLabel: "Not won",
  },
  recommendations: {
    pending: {
      branchId: "extra-day",
      title: "Keep the original bookable; hold one flexible night.",
      rationale: "The result arrives before the free-cancellation window. A refundable Page night preserves both outcomes without forcing a decision today.",
      actions: ["Hold one refundable Page night", "Set a reminder for the cancellation deadline"],
    },
    positive: {
      branchId: "fly",
      title: "Fly to Vegas and protect a full hiking day.",
      rationale: "Flying removes 15 hours of driving and fits The Wave into six days without dropping Antelope Canyon or Monument Valley.",
      actions: ["Price SFO–LAS flights", "Move the Page hotel", "Confirm permit pickup details"],
    },
    negative: {
      branchId: "loop",
      title: "Keep the six-day loop—no replanning required.",
      rationale: "The original loop keeps all five parks and every current booking. The flexible Page hold can now be released.",
      actions: ["Cancel the flexible Page hold", "Confirm Antelope Canyon time"],
    },
  },
  branches: [
    {
      id: "loop",
      name: "Keep the 6-day loop",
      subtitle: "Best if the permit doesn’t happen",
      days: 6,
      cost: 1780,
      transportMode: "Drive my car",
      transitHours: 39,
      driveHours: 39,
      luggageFlexibility: "High",
      bookingComplexity: "Low",
      fatigue: 9,
      experienceScore: 7,
      flexibility: "Low",
      summary: "Keep the route and all current bookings.",
      changes: ["Keep every existing hotel", "Use the Page day for Antelope Canyon", "No reservation changes"],
      tradeoffs: ["The Wave", "Recovery time", "Daylight buffer"],
      timeline: [
        { day: "01", title: "Bay Area → Las Vegas", detail: "Transit day · 9h" },
        { day: "02", title: "Zion → Bryce", detail: "Two parks · arrive after dark" },
        { day: "03", title: "Bryce → Page", detail: "Sunrise + Lake Powell" },
        { day: "04", title: "Page → Monument Valley", detail: "Antelope slot · 1:15 PM" },
        { day: "05", title: "Grand Canyon → Las Vegas", detail: "Sunrise + 7h driving" },
        { day: "06", title: "Las Vegas → Bay Area", detail: "Transit day · 9h" },
      ],
    },
    {
      id: "extra-day",
      name: "Win + add one day",
      subtitle: "The fullest experience, with room to breathe",
      days: 7,
      cost: 2260,
      transportMode: "Drive my car",
      transitHours: 41,
      driveHours: 41,
      luggageFlexibility: "High",
      bookingComplexity: "Medium",
      fatigue: 7,
      experienceScore: 9,
      flexibility: "High",
      summary: "Add a Page night and give The Wave a protected day.",
      changes: ["Add one Page-area night", "Protect a full day for The Wave", "Move Antelope Canyon to Day 5"],
      tradeoffs: ["One workday", "$480 more", "Original hotel sequence"],
      timeline: [
        { day: "01", title: "Bay Area → Las Vegas", detail: "Transit day · 9h" },
        { day: "02", title: "Zion → Bryce", detail: "Two parks · arrive after dark" },
        { day: "03", title: "Bryce → Page", detail: "Sunrise + early finish" },
        { day: "04", title: "The Wave", detail: "Full hiking day · permit required" },
        { day: "05", title: "Page → Monument Valley", detail: "Antelope + sunset" },
        { day: "06", title: "Grand Canyon → Las Vegas", detail: "More daylight buffer" },
        { day: "07", title: "Las Vegas → Bay Area", detail: "Transit day · 9h" },
      ],
    },
    {
      id: "fly",
      name: "Win + fly to Vegas",
      subtitle: "Fit The Wave into six days without the road grind",
      days: 6,
      cost: 2480,
      transportMode: "Fly + rental car",
      transitHours: 30,
      driveHours: 24,
      luggageFlexibility: "Medium",
      bookingComplexity: "High",
      fatigue: 6,
      experienceScore: 9,
      flexibility: "Medium",
      summary: "Spend more to remove both long transit days.",
      changes: ["Replace two transit days with flights", "Pick up the car in Las Vegas", "Use recovered time for The Wave"],
      tradeoffs: ["$700 more", "Your own car", "Flexible luggage"],
      timeline: [
        { day: "01", title: "Fly to Vegas → Zion", detail: "Land by 9 AM" },
        { day: "02", title: "Bryce → Page", detail: "Sunrise + relaxed afternoon" },
        { day: "03", title: "The Wave", detail: "Full hiking day · permit required" },
        { day: "04", title: "Page → Monument Valley", detail: "Antelope + sunset" },
        { day: "05", title: "Grand Canyon → Las Vegas", detail: "South Rim · 4h" },
        { day: "06", title: "Fly to Bay Area", detail: "Home by afternoon" },
      ],
    },
  ],
  checklist: [
    { id: "sample-1", label: "Enter The Wave lottery", dueDate: "Jul 16", kind: "decide", done: true },
    { id: "sample-2", label: "Hold refundable Page hotel", dueDate: "Jul 18", kind: "book", done: false },
    { id: "sample-3", label: "Release unused hotel branch", dueDate: "Jul 19", kind: "cancel", done: false },
  ],
  updatedAt: "2026-07-16T12:00:00.000Z",
};
