import type { TripDocument } from "./trip-types";

export const sampleTrip: TripDocument = {
  id: "sample-southwest-loop",
  title: "What if we win The Wave?",
  destination: "Southwest loop",
  dateSummary: "Apr 30–May 5",
  travelers: "2 travelers",
  budget: "$2,500",
  sourceNotes: "Bay Area road trip through Zion, Bryce, Page, Monument Valley and Grand Canyon. The Wave permit may change the route.",
  inputSummary: {
    origin: "San Francisco Bay Area",
    existingPlan: "Drive from the Bay Area to Las Vegas, then loop through Zion, Bryce, Page, Monument Valley and Grand Canyon before driving home.",
    places: "Las Vegas, Zion, Bryce, Page, The Wave, Antelope Canyon, Monument Valley, Grand Canyon",
    lockedItems: "Six-day window; Antelope Canyon tour; return home by Sunday night",
    movableItems: "Page hotel; Monument Valley day; Grand Canyon sunrise",
    optionalItems: "Lake Powell; Las Vegas evening",
    transportModes: ["Drive my car", "Fly + rental car"],
  },
  decision: {
    name: "The Wave lottery",
    question: "Did we win The Wave permit?",
    decisionDate: "Jul 18",
    status: "pending",
    positiveLabel: "Won",
    negativeLabel: "Not won",
  },
  recommendations: {
    pending: {
      branchId: "extra-day",
      title: "Keep the original bookable; hold one flexible night.",
      rationale: "The result arrives before the free-cancellation window. A refundable Page night preserves both outcomes without forcing a decision today.",
      actions: ["Hold one refundable Page night", "Set a reminder for the cancellation deadline"],
    },
    positive: {
      branchId: "fly",
      title: "Fly to Vegas and protect a full hiking day.",
      rationale: "Flying removes 15 hours of driving and fits The Wave into six days without dropping Antelope Canyon or Monument Valley.",
      actions: ["Price SFO–LAS flights", "Move the Page hotel", "Confirm permit pickup details"],
    },
    negative: {
      branchId: "loop",
      title: "Keep the six-day loop—no replanning required.",
      rationale: "The original loop keeps all five parks and every current booking. The flexible Page hold can now be released.",
      actions: ["Cancel the flexible Page hold", "Confirm Antelope Canyon time"],
    },
  },
  branches: [
    {
      id: "loop",
      name: "Keep the 6-day loop",
      subtitle: "Best if the permit doesn’t happen",
      days: 6,
      cost: 1780,
      transportMode: "Drive my car",
      transitHours: 39,
      driveHours: 39,
      luggageFlexibility: "High",
      bookingComplexity: "Low",
      fatigue: 9,
      experienceScore: 7,
      flexibility: "Low",
      summary: "Keep the route and all current bookings.",
      changes: ["Keep every existing hotel", "Use the Page day for Antelope Canyon", "No reservation changes"],
      tradeoffs: ["The Wave", "Recovery time", "Daylight buffer"],
      timeline: [
        { day: "01", title: "Bay Area → Las Vegas", detail: "Transit day · 9h" },
        { day: "02", title: "Zion → Bryce", detail: "Two parks · arrive after dark" },
        { day: "03", title: "Bryce → Page", detail: "Sunrise + Lake Powell" },
        { day: "04", title: "Page → Monument Valley", detail: "Antelope slot · 1:15 PM" },
        { day: "05", title: "Grand Canyon → Las Vegas", detail: "Sunrise + 7h driving" },
        { day: "06", title: "Las Vegas → Bay Area", detail: "Transit day · 9h" },
      ],
    },
    {
      id: "extra-day",
      name: "Win + add one day",
      subtitle: "The fullest experience, with room to breathe",
      days: 7,
      cost: 2260,
      transportMode: "Drive my car",
      transitHours: 41,
      driveHours: 41,
      luggageFlexibility: "High",
      bookingComplexity: "Medium",
      fatigue: 7,
      experienceScore: 9,
      flexibility: "High",
      summary: "Add a Page night and give The Wave a protected day.",
      changes: ["Add one Page-area night", "Protect a full day for The Wave", "Move Antelope Canyon to Day 5"],
      tradeoffs: ["One workday", "$480 more", "Original hotel sequence"],
      timeline: [
        { day: "01", title: "Bay Area → Las Vegas", detail: "Transit day · 9h" },
        { day: "02", title: "Zion → Bryce", detail: "Two parks · arrive after dark" },
        { day: "03", title: "Bryce → Page", detail: "Sunrise + early finish" },
        { day: "04", title: "The Wave", detail: "Full hiking day · permit required" },
        { day: "05", title: "Page → Monument Valley", detail: "Antelope + sunset" },
        { day: "06", title: "Grand Canyon → Las Vegas", detail: "More daylight buffer" },
        { day: "07", title: "Las Vegas → Bay Area", detail: "Transit day · 9h" },
      ],
    },
    {
      id: "fly",
      name: "Win + fly to Vegas",
      subtitle: "Fit The Wave into six days without the road grind",
      days: 6,
      cost: 2480,
      transportMode: "Fly + rental car",
      transitHours: 30,
      driveHours: 24,
      luggageFlexibility: "Medium",
      bookingComplexity: "High",
      fatigue: 6,
      experienceScore: 9,
      flexibility: "Medium",
      summary: "Spend more to remove both long transit days.",
      changes: ["Replace two transit days with flights", "Pick up the car in Las Vegas", "Use recovered time for The Wave"],
      tradeoffs: ["$700 more", "Your own car", "Flexible luggage"],
      timeline: [
        { day: "01", title: "Fly to Vegas → Zion", detail: "Land by 9 AM" },
        { day: "02", title: "Bryce → Page", detail: "Sunrise + relaxed afternoon" },
        { day: "03", title: "The Wave", detail: "Full hiking day · permit required" },
        { day: "04", title: "Page → Monument Valley", detail: "Antelope + sunset" },
        { day: "05", title: "Grand Canyon → Las Vegas", detail: "South Rim · 4h" },
        { day: "06", title: "Fly to Bay Area", detail: "Home by afternoon" },
      ],
    },
  ],
  checklist: [
    { id: "sample-1", label: "Enter The Wave lottery", dueDate: "Jul 16", kind: "decide", done: true },
    { id: "sample-2", label: "Hold refundable Page hotel", dueDate: "Jul 18", kind: "book", done: false },
    { id: "sample-3", label: "Release unused hotel branch", dueDate: "Jul 19", kind: "cancel", done: false },
  ],
  updatedAt: "2026-07-16T12:00:00.000Z",
};

export const sampleTripZh: TripDocument = {
  id: "sample-southwest-loop",
  title: "如果抽中了 The Wave，路线怎么改？",
  destination: "美西大环线",
  dateSummary: "4 月 30 日–5 月 5 日",
  travelers: "2 人",
  budget: "$2,500",
  sourceNotes: "从湾区出发，途经锡安、布莱斯、佩吉、纪念碑谷和大峡谷。The Wave 抽签结果可能改变整条路线。",
  inputSummary: {
    origin: "旧金山湾区",
    existingPlan: "从湾区自驾到拉斯维加斯，再依次经过锡安、布莱斯、佩吉、纪念碑谷和大峡谷，最后开车回家。",
    places: "拉斯维加斯、锡安、布莱斯、佩吉、The Wave、羚羊谷、纪念碑谷、大峡谷",
    lockedItems: "总共 6 天；羚羊谷预订；周日晚前回家",
    movableItems: "佩吉酒店；纪念碑谷日期；大峡谷日出",
    optionalItems: "鲍威尔湖；拉斯维加斯夜游",
    transportModes: ["自驾", "飞机 + 租车"],
  },
  decision: {
    name: "The Wave 抽签",
    question: "我们抽中 The Wave 许可了吗？",
    decisionDate: "7 月 18 日",
    status: "pending",
    positiveLabel: "抽中了",
    negativeLabel: "没抽中",
  },
  recommendations: {
    pending: {
      branchId: "extra-day",
      title: "保留原计划可预订状态，同时锁一晚可退款住宿。",
      rationale: "抽签结果会在免费取消期限前公布。一晚可退款的佩吉住宿能同时保留两种走法，不必现在就押注。",
      actions: ["预留一晚可退款的佩吉住宿", "为免费取消截止日设置提醒"],
    },
    positive: {
      branchId: "fly",
      title: "飞到拉斯维加斯，保住一整天徒步时间。",
      rationale: "坐飞机可以减少 15 小时驾驶，在 6 天内加入 The Wave，同时不必放弃羚羊谷和纪念碑谷。",
      actions: ["查询 SFO–LAS 机票总价", "调整佩吉酒店", "确认许可领取细节"],
    },
    negative: {
      branchId: "loop",
      title: "保留 6 日环线，不需要重新规划。",
      rationale: "原路线保留五个国家公园和所有现有预订；现在可以取消备用的佩吉住宿。",
      actions: ["取消备用的佩吉住宿", "确认羚羊谷入场时间"],
    },
  },
  branches: [
    {
      id: "loop",
      name: "保留 6 日环线",
      subtitle: "没抽中许可时最稳妥",
      days: 6,
      cost: 1780,
      transportMode: "自驾",
      transitHours: 39,
      driveHours: 39,
      luggageFlexibility: "High",
      bookingComplexity: "Low",
      fatigue: 9,
      experienceScore: 7,
      flexibility: "Low",
      summary: "保留原路线和全部现有预订。",
      changes: ["保留每一家现有酒店", "佩吉当天游览羚羊谷", "无需修改预订"],
      tradeoffs: ["The Wave", "恢复时间", "白天行车余量"],
      timeline: [
        { day: "01", title: "湾区 → 拉斯维加斯", detail: "交通日 · 9 小时" },
        { day: "02", title: "锡安 → 布莱斯", detail: "一天两个公园 · 天黑后抵达" },
        { day: "03", title: "布莱斯 → 佩吉", detail: "日出 + 鲍威尔湖" },
        { day: "04", title: "佩吉 → 纪念碑谷", detail: "羚羊谷 · 下午 1:15" },
        { day: "05", title: "大峡谷 → 拉斯维加斯", detail: "日出 + 驾驶 7 小时" },
        { day: "06", title: "拉斯维加斯 → 湾区", detail: "交通日 · 9 小时" },
      ],
    },
    {
      id: "extra-day",
      name: "抽中 + 增加一天",
      subtitle: "体验最完整，也有喘息空间",
      days: 7,
      cost: 2260,
      transportMode: "自驾",
      transitHours: 41,
      driveHours: 41,
      luggageFlexibility: "High",
      bookingComplexity: "Medium",
      fatigue: 7,
      experienceScore: 9,
      flexibility: "High",
      summary: "在佩吉多住一晚，为 The Wave 留出完整一天。",
      changes: ["增加一晚佩吉附近住宿", "为 The Wave 保留整天", "把羚羊谷移到第 5 天"],
      tradeoffs: ["一个工作日", "多花 $480", "原酒店顺序"],
      timeline: [
        { day: "01", title: "湾区 → 拉斯维加斯", detail: "交通日 · 9 小时" },
        { day: "02", title: "锡安 → 布莱斯", detail: "一天两个公园 · 天黑后抵达" },
        { day: "03", title: "布莱斯 → 佩吉", detail: "看日出 + 提前收工" },
        { day: "04", title: "The Wave", detail: "全天徒步 · 需要许可" },
        { day: "05", title: "佩吉 → 纪念碑谷", detail: "羚羊谷 + 日落" },
        { day: "06", title: "大峡谷 → 拉斯维加斯", detail: "更多白天行车余量" },
        { day: "07", title: "拉斯维加斯 → 湾区", detail: "交通日 · 9 小时" },
      ],
    },
    {
      id: "fly",
      name: "抽中 + 飞到拉斯维加斯",
      subtitle: "6 天内加入 The Wave，避免长途自驾",
      days: 6,
      cost: 2480,
      transportMode: "飞机 + 租车",
      transitHours: 30,
      driveHours: 24,
      luggageFlexibility: "Medium",
      bookingComplexity: "High",
      fatigue: 6,
      experienceScore: 9,
      flexibility: "Medium",
      summary: "多花一些钱，去掉往返两个超长交通日。",
      changes: ["用飞机替代两个长途交通日", "在拉斯维加斯取车", "把省下的时间留给 The Wave"],
      tradeoffs: ["多花 $700", "不能开自己的车", "行李自由度"],
      timeline: [
        { day: "01", title: "飞到拉斯维加斯 → 锡安", detail: "上午 9 点前落地" },
        { day: "02", title: "布莱斯 → 佩吉", detail: "看日出 + 轻松的下午" },
        { day: "03", title: "The Wave", detail: "全天徒步 · 需要许可" },
        { day: "04", title: "佩吉 → 纪念碑谷", detail: "羚羊谷 + 日落" },
        { day: "05", title: "大峡谷 → 拉斯维加斯", detail: "南缘 · 4 小时" },
        { day: "06", title: "飞回湾区", detail: "下午到家" },
      ],
    },
  ],
  checklist: [
    { id: "sample-1", label: "参加 The Wave 抽签", dueDate: "7 月 16 日", kind: "decide", done: true },
    { id: "sample-2", label: "预留可退款的佩吉酒店", dueDate: "7 月 18 日", kind: "book", done: false },
    { id: "sample-3", label: "取消未采用路线的酒店", dueDate: "7 月 19 日", kind: "cancel", done: false },
  ],
  updatedAt: "2026-07-16T12:00:00.000Z",
};
