import type { TripDocument } from "./trip-types";

export const sampleTrip: TripDocument = {
  id: "sample-southwest-loop",
  title: "What if we win The Wave?",
  destination: "Southwest loop",
  dateSummary: "Apr 30–May 5",
  travelers: "2 travelers",
  budget: "$2,500",
  sourceNotes: "Bay Area road trip through Zion, Bryce, Page, Monument Valley and Grand Canyon. The Wave permit may change the route.",
  inputSummary: {
    origin: "San Francisco Bay Area",
    existingPlan: "Drive from the Bay Area to Las Vegas, then loop through Zion, Bryce, Page, Monument Valley and Grand Canyon before driving home.",
    places: "Las Vegas, Zion, Bryce, Page, The Wave, Antelope Canyon, Monument Valley, Grand Canyon",
    lockedItems: "Six-day window; Antelope Canyon tour; return home by Sunday night",
    movableItems: "Page hotel; Monument Valley day; Grand Canyon sunrise",
    optionalItems: "Lake Powell; Las Vegas evening",
    transportModes: ["Drive my car", "Fly + rental car"],
  },
  decision: {
    name: "The Wave lottery",
    question: "Did we win The Wave permit?",
    decisionDate: "Jul 18",
    status: "pending",
    positiveLabel: "Won",
    negativeLabel: "Not won",
  },
  recommendations: {
    pending: {
      branchId: "extra-day",
      title: "Keep the original bookable; hold one flexible night.",
      rationale: "The result arrives before the free-cancellation window. A refundable Page night preserves both outcomes without forcing a decision today.",
      actions: ["Hold one refundable Page night", "Set a reminder for the cancellation deadline"],
    },
    positive: {
      branchId: "fly",
      title: "Fly to Vegas and protect a full hiking day.",
      rationale: "Flying removes 15 hours of driving and fits The Wave into six days without dropping Antelope Canyon or Monument Valley.",
      actions: ["Price SFO–LAS flights", "Move the Page hotel", "Confirm permit pickup details"],
    },
    negative: {
      branchId: "loop",
      title: "Keep the six-day loop—no replanning required.",
      rationale: "The original loop keeps all five parks and every current booking. The flexible Page hold can now be released.",
      actions: ["Cancel the flexible Page hold", "Confirm Antelope Canyon time"],
    },
  },
  branches: [
    {
      id: "loop",
      name: "Keep the 6-day loop",
      subtitle: "Best if the permit doesn’t happen",
      days: 6,
      cost: 1780,
      transportMode: "Drive my car",
      transitHours: 39,
      driveHours: 39,
      luggageFlexibility: "High",
      bookingComplexity: "Low",
      fatigue: 9,
      experienceScore: 7,
      flexibility: "Low",
      outcomes: ["pending", "negative"],
      summary: "Keep the route and all current bookings.",
      changes: ["Keep every existing hotel", "Use the Page day for Antelope Canyon", "No reservation changes"],
      tradeoffs: ["The Wave", "Recovery time", "Daylight buffer"],
      timeline: [
        { day: "01", title: "Bay Area → Las Vegas", detail: "Transit day · 9h" },
        { day: "02", title: "Zion → Bryce", detail: "Two parks · arrive after dark" },
        { day: "03", title: "Bryce → Page", detail: "Sunrise + Lake Powell" },
        { day: "04", title: "Page → Monument Valley", detail: "Antelope slot · 1:15 PM" },
        { day: "05", title: "Grand Canyon → Las Vegas", detail: "Sunrise + 7h driving" },
        { day: "06", title: "Las Vegas → Bay Area", detail: "Transit day · 9h" },
      ],
    },
    {
      id: "extra-day",
      name: "Win + add one day",
      subtitle: "The fullest experience, with room to breathe",
      days: 7,
      cost: 2260,
      transportMode: "Drive my car",
      transitHours: 41,
      driveHours: 41,
      luggageFlexibility: "High",
      bookingComplexity: "Medium",
      fatigue: 7,
      experienceScore: 9,
      flexibility: "High",
      outcomes: ["pending", "positive"],
      summary: "Add a Page night and give The Wave a protected day.",
      changes: ["Add one Page-area night", "Protect a full day for The Wave", "Move Antelope Canyon to Day 5"],
      tradeoffs: ["One workday", "$480 more", "Original hotel sequence"],
      timeline: [
        { day: "01", title: "Bay Area → Las Vegas", detail: "Transit day · 9h" },
        { day: "02", title: "Zion → Bryce", detail: "Two parks · arrive after dark" },
        { day: "03", title: "Bryce → Page", detail: "Sunrise + early finish" },
        { day: "04", title: "The Wave", detail: "Full hiking day · permit required" },
        { day: "05", title: "Page → Monument Valley", detail: "Antelope + sunset" },
        { day: "06", title: "Grand Canyon → Las Vegas", detail: "More daylight buffer" },
        { day: "07", title: "Las Vegas → Bay Area", detail: "Transit day · 9h" },
      ],
    },
    {
      id: "fly",
      name: "Win + fly to Vegas",
      subtitle: "Fit The Wave into six days without the road grind",
      days: 6,
      cost: 2480,
      transportMode: "Fly + rental car",
      transitHours: 30,
      driveHours: 24,
      luggageFlexibility: "Medium",
      bookingComplexity: "High",
      fatigue: 6,
      experienceScore: 9,
      flexibility: "Medium",
      outcomes: ["pending", "positive"],
      summary: "Spend more to remove both long transit days.",
      changes: ["Replace two transit days with flights", "Pick up the car in Las Vegas", "Use recovered time for The Wave"],
      tradeoffs: ["$700 more", "Your own car", "Flexible luggage"],
      timeline: [
        { day: "01", title: "Fly to Vegas → Zion", detail: "Land by 9 AM" },
        { day: "02", title: "Bryce → Page", detail: "Sunrise + relaxed afternoon" },
        { day: "03", title: "The Wave", detail: "Full hiking day · permit required" },
        { day: "04", title: "Page → Monument Valley", detail: "Antelope + sunset" },
        { day: "05", title: "Grand Canyon → Las Vegas", detail: "South Rim · 4h" },
        { day: "06", title: "Fly to Bay Area", detail: "Home by afternoon" },
      ],
    },
  ],
  checklist: [
    { id: "sample-1", label: "Enter The Wave lottery", dueDate: "Jul 16", kind: "decide", done: true },
    { id: "sample-2", label: "Hold refundable Page hotel", dueDate: "Jul 18", kind: "book", done: false },
    { id: "sample-3", label: "Release unused hotel branch", dueDate: "Jul 19", kind: "cancel", done: false },
  ],
  updatedAt: "2026-07-16T12:00:00.000Z",
};

export const sampleTripZh: TripDocument = {
  id: "sample-southwest-loop",
  title: "如果抽中了 The Wave，路线怎么改？",
  destination: "美西环线",
  dateSummary: "4 月 30 日–5 月 5 日",
  travelers: "2 人",
  budget: "$2,500",
  sourceNotes: "从湾区出发，经过锡安、布莱斯、佩吉、纪念碑谷和大峡谷。要是抽中 The Wave，整条路线都得跟着调整。",
  inputSummary: {
    origin: "旧金山湾区",
    existingPlan: "从湾区开车到拉斯维加斯，再走锡安、布莱斯、佩吉、纪念碑谷和大峡谷，最后开回家。",
    places: "拉斯维加斯、锡安、布莱斯、佩吉、The Wave、羚羊谷、纪念碑谷、大峡谷",
    lockedItems: "只有 6 天；羚羊谷已经订好；周日晚前必须到家",
    movableItems: "哪天住佩吉；纪念碑谷放在哪天；大峡谷日出",
    optionalItems: "鲍威尔湖；拉斯维加斯夜游",
    transportModes: ["自驾", "飞机 + 租车"],
  },
  decision: {
    name: "The Wave 抽签",
    question: "我们抽中 The Wave 许可了吗？",
    decisionDate: "7 月 18 日",
    status: "pending",
    positiveLabel: "抽中了",
    negativeLabel: "没抽中",
  },
  recommendations: {
    pending: {
      branchId: "extra-day",
      title: "先按原计划订，同时留一晚可退的佩吉住宿。",
      rationale: "抽签结果会赶在免费取消期限前出来。多留一晚可退的住宿，两种走法都还有余地，不用现在就押一个答案。",
      actions: ["先订一晚可退款的佩吉住宿", "给免费取消截止时间设个提醒"],
    },
    positive: {
      branchId: "fly",
      title: "飞到拉斯维加斯，给 The Wave 留出完整一天。",
      rationale: "这样能少开 15 个小时，6 天里也塞得下 The Wave，还不用放弃羚羊谷和纪念碑谷。",
      actions: ["查一下 SFO–LAS 往返机票总价", "调整佩吉酒店日期", "确认许可去哪里领"],
    },
    negative: {
      branchId: "loop",
      title: "继续走原来的 6 日环线，不用重排。",
      rationale: "五个公园和已经订好的项目都不受影响，之前多留的那晚佩吉住宿也可以退掉了。",
      actions: ["退掉备用的佩吉住宿", "再确认一次羚羊谷入场时间"],
    },
  },
  branches: [
    {
      id: "loop",
      name: "照原来的 6 日环线走",
      subtitle: "没抽中时最省事",
      days: 6,
      cost: 1780,
      transportMode: "自驾",
      transitHours: 39,
      driveHours: 39,
      luggageFlexibility: "High",
      bookingComplexity: "Low",
      fatigue: 9,
      experienceScore: 7,
      flexibility: "Low",
      outcomes: ["pending", "negative"],
      summary: "路线和已经订好的东西都不用动。",
      changes: ["所有酒店先不动", "在佩吉那天去羚羊谷", "不用退订或重订"],
      tradeoffs: ["去不了 The Wave", "几乎没有休息时间", "更容易天黑后开车"],
      timeline: [
        { day: "01", title: "湾区 → 拉斯维加斯", detail: "交通日 · 9 小时" },
        { day: "02", title: "锡安 → 布莱斯", detail: "一天跑两个公园 · 天黑后到" },
        { day: "03", title: "布莱斯 → 佩吉", detail: "日出 + 鲍威尔湖" },
        { day: "04", title: "佩吉 → 纪念碑谷", detail: "羚羊谷 · 下午 1:15" },
        { day: "05", title: "大峡谷 → 拉斯维加斯", detail: "看日出 + 开车 7 小时" },
        { day: "06", title: "拉斯维加斯 → 湾区", detail: "交通日 · 9 小时" },
      ],
    },
    {
      id: "extra-day",
      name: "抽中后多玩一天",
      subtitle: "玩得最完整，也没那么赶",
      days: 7,
      cost: 2260,
      transportMode: "自驾",
      transitHours: 41,
      driveHours: 41,
      luggageFlexibility: "High",
      bookingComplexity: "Medium",
      fatigue: 7,
      experienceScore: 9,
      flexibility: "High",
      outcomes: ["pending", "positive"],
      summary: "在佩吉多住一晚，单独拿一天去 The Wave。",
      changes: ["在佩吉附近多住一晚", "拿出完整一天去 The Wave", "羚羊谷挪到第 5 天"],
      tradeoffs: ["多请一天假", "多花 $480", "酒店日期要跟着改"],
      timeline: [
        { day: "01", title: "湾区 → 拉斯维加斯", detail: "交通日 · 9 小时" },
        { day: "02", title: "锡安 → 布莱斯", detail: "一天跑两个公园 · 天黑后到" },
        { day: "03", title: "布莱斯 → 佩吉", detail: "看日出 + 提前收工" },
        { day: "04", title: "The Wave", detail: "全天徒步 · 需要许可" },
        { day: "05", title: "佩吉 → 纪念碑谷", detail: "羚羊谷 + 日落" },
        { day: "06", title: "大峡谷 → 拉斯维加斯", detail: "不用太担心开夜路" },
        { day: "07", title: "拉斯维加斯 → 湾区", detail: "交通日 · 9 小时" },
      ],
    },
    {
      id: "fly",
      name: "抽中后飞到拉斯维加斯",
      subtitle: "还是 6 天，但少开很多路",
      days: 6,
      cost: 2480,
      transportMode: "飞机 + 租车",
      transitHours: 30,
      driveHours: 24,
      luggageFlexibility: "Medium",
      bookingComplexity: "High",
      fatigue: 6,
      experienceScore: 9,
      flexibility: "Medium",
      outcomes: ["pending", "positive"],
      summary: "多花一点钱，省掉往返两个超长驾驶日。",
      changes: ["往返长途改坐飞机", "到拉斯维加斯再取车", "省下来的时间留给 The Wave"],
      tradeoffs: ["多花 $700", "不能开自己的车", "行李要按航空规定来"],
      timeline: [
        { day: "01", title: "飞到拉斯维加斯 → 锡安", detail: "上午 9 点前落地" },
        { day: "02", title: "布莱斯 → 佩吉", detail: "看完日出，下午不用赶路" },
        { day: "03", title: "The Wave", detail: "全天徒步 · 需要许可" },
        { day: "04", title: "佩吉 → 纪念碑谷", detail: "羚羊谷 + 日落" },
        { day: "05", title: "大峡谷 → 拉斯维加斯", detail: "南缘 · 4 小时" },
        { day: "06", title: "飞回湾区", detail: "下午到家" },
      ],
    },
  ],
  checklist: [
    { id: "sample-1", label: "报名 The Wave 抽签", dueDate: "7 月 16 日", kind: "decide", done: true },
    { id: "sample-2", label: "先订一晚可退的佩吉酒店", dueDate: "7 月 18 日", kind: "book", done: false },
    { id: "sample-3", label: "退掉最后没用上的酒店", dueDate: "7 月 19 日", kind: "cancel", done: false },
  ],
  updatedAt: "2026-07-16T12:00:00.000Z",
};

export const sampleHawaiiTrip: TripDocument = {
  id: "sample-hawaii-big-island",
  title: "What if the volcano or summit weather changes?",
  destination: "Hawaii Big Island",
  dateSummary: "Feb 16–23 · 7 days",
  travelers: "2 travelers",
  budget: "$4,000",
  sourceNotes: "A real seven-day Big Island trip with a fixed manta-ray dive, volcano viewing, Mauna Kea weather, and safer swimming constraints.",
  inputSummary: {
    origin: "San Francisco Bay Area",
    existingPlan: "Fly to Kona, split the week between Kona, Volcano and Hilo, then return along the north coast. Keep the manta-ray dive and avoid difficult open-water swimming.",
    places: "Kona, manta-ray night dive, Volcanoes National Park, Mauna Kea, Hilo, Waimea, north coast",
    lockedItems: "Return flight; manta-ray booking; seven-day window",
    movableItems: "Mauna Kea evening; Volcano night; Hilo waterfalls",
    optionalItems: "Hilo market; second Volcano visit; scenic beach detour",
    transportModes: ["Fly + rental car"],
  },
  decision: {
    name: "Volcano + summit conditions",
    question: "Are eruption viewing and Mauna Kea conditions favorable?",
    decisionDate: "Check 48 hours before",
    status: "pending",
    positiveLabel: "Favorable",
    negativeLabel: "Not favorable",
  },
  recommendations: {
    pending: {
      branchId: "weather-window",
      title: "Keep one evening movable and follow the best weather window.",
      rationale: "Kona, Volcano and Hilo can stay fixed. Only one evening needs to move for the summit or eruption window.",
      actions: ["Keep one evening unbooked", "Check park alerts and summit weather 48 hours before"],
    },
    positive: {
      branchId: "live-event",
      title: "Use the good window for the rare experience.",
      rationale: "Move an optional Hilo stop and spend the favorable evening on the summit or at the park.",
      actions: ["Confirm official access", "Pack layers and lights", "Move the optional Hilo afternoon"],
    },
    negative: {
      branchId: "coast-first",
      title: "Stop chasing conditions and slow down on the coast.",
      rationale: "Manta rays, protected snorkeling and the north coast still make a strong trip without unsafe backtracking.",
      actions: ["Confirm the manta operator", "Choose a protected snorkel beach", "Release the flexible Volcano night"],
    },
  },
  branches: [
    {
      id: "weather-window",
      name: "Keep one evening flexible",
      subtitle: "Move one evening, not the whole trip",
      days: 7,
      cost: 3950,
      transportMode: "Fly + rental car",
      transitHours: 18,
      driveHours: 18,
      luggageFlexibility: "Medium",
      bookingComplexity: "Medium",
      fatigue: 7,
      experienceScore: 9,
      flexibility: "High",
      outcomes: ["pending", "positive", "negative"],
      summary: "Keep both coasts fixed while one evening follows the clearest conditions.",
      changes: ["Leave one evening movable", "Use the clearest window for Mauna Kea or Volcano"],
      tradeoffs: ["One unplanned evening", "Possible backtracking"],
      timeline: [
        { day: "Day 1–2", title: "Kona coast", detail: "Manta rays and protected snorkeling" },
        { day: "Day 3–4", title: "Volcano district", detail: "Park plus a movable summit evening" },
        { day: "Day 5–7", title: "Hilo and north coast", detail: "Waterfalls and scenic return" },
      ],
    },
    {
      id: "live-event",
      name: "Chase the live event",
      subtitle: "Protect the rare experience when conditions line up",
      days: 7,
      cost: 4100,
      transportMode: "Fly + rental car",
      transitHours: 21,
      driveHours: 21,
      luggageFlexibility: "Medium",
      bookingComplexity: "High",
      fatigue: 8,
      experienceScore: 10,
      flexibility: "Medium",
      outcomes: ["positive"],
      summary: "Return to the park or summit during the best official window and drop optional stops.",
      changes: ["Replace the optional Hilo afternoon", "Drive back only when official conditions are favorable"],
      tradeoffs: ["Rainbow Falls or market time", "Three extra driving hours"],
      timeline: [
        { day: "Day 1–5", title: "Keep the core route", detail: "Kona → Volcano → Hilo" },
        { day: "Day 6", title: "Return for the live event", detail: "Only if official conditions are favorable" },
        { day: "Day 7", title: "North coast to Kona", detail: "Keep the flight and scenic return" },
      ],
    },
    {
      id: "coast-first",
      name: "Slow coast fallback",
      subtitle: "The easier week when conditions disappoint",
      days: 7,
      cost: 3700,
      transportMode: "Fly + rental car",
      transitHours: 15,
      driveHours: 15,
      luggageFlexibility: "Medium",
      bookingComplexity: "Low",
      fatigue: 5,
      experienceScore: 8,
      flexibility: "Medium",
      outcomes: ["pending", "negative"],
      summary: "Avoid chasing weather and spend the recovered time on beaches and the north coast.",
      changes: ["Skip the second park or summit attempt", "Add a slower north-coast day"],
      tradeoffs: ["No eruption viewing", "No summit sunset"],
      timeline: [
        { day: "Day 1–3", title: "Kona", detail: "Manta rays and gentle water activities" },
        { day: "Day 4–5", title: "Volcano and Hilo", detail: "Daylight park visit and waterfalls" },
        { day: "Day 6–7", title: "North coast", detail: "Waimea and scenic beaches" },
      ],
    },
  ],
  checklist: [
    { id: "hawaii-1", label: "Confirm manta-ray cancellation terms", dueDate: "Before free cancellation", kind: "check", done: true },
    { id: "hawaii-2", label: "Check NPS alerts and summit weather", dueDate: "48 hours before", kind: "decide", done: false },
    { id: "hawaii-3", label: "Release the unused flexible booking", dueDate: "Before cutoff", kind: "cancel", done: false },
  ],
  updatedAt: "2026-07-20T12:00:00.000Z",
};

export const sampleHawaiiTripZh: TripDocument = {
  id: "sample-hawaii-big-island",
  title: "火山和山顶天气变了，行程怎么跟着改？",
  destination: "夏威夷大岛",
  dateSummary: "2 月 16–23 日 · 7 天",
  travelers: "2 人",
  budget: "$4,000",
  sourceNotes: "一趟真实的大岛 7 日行程：魔鬼鱼夜潜已经订好，还想看火山和冒纳凯阿，同时要避开难度太高的游泳项目。",
  inputSummary: {
    origin: "旧金山湾区",
    existingPlan: "飞到科纳，在科纳、火山村和希洛分段住宿，最后沿北岸回到科纳。魔鬼鱼夜潜不能动，也不安排难度太高的开放水域游泳。",
    places: "科纳、魔鬼鱼夜潜、火山国家公园、冒纳凯阿、希洛、威美亚、北岸",
    lockedItems: "返程航班；魔鬼鱼预订；一共只有 7 天",
    movableItems: "冒纳凯阿放哪晚；火山村住哪晚；希洛瀑布放哪天",
    optionalItems: "希洛市场；再去一次火山；顺路去海滩",
    transportModes: ["飞机 + 租车"],
  },
  decision: {
    name: "火山和山顶天气",
    question: "火山观景和冒纳凯阿的天气合适吗？",
    decisionDate: "提前 48 小时确认",
    status: "pending",
    positiveLabel: "天气合适",
    negativeLabel: "天气不合适",
  },
  recommendations: {
    pending: {
      branchId: "weather-window",
      title: "先留一个晚上别排死，等天气更清楚再决定。",
      rationale: "科纳、火山村和希洛的住宿都不用动，只需要让一个晚上跟着火山或山顶天气调整。",
      actions: ["留一个晚上先不订活动", "提前 48 小时看公园通知和山顶天气"],
    },
    positive: {
      branchId: "live-event",
      title: "天气合适，就把难得的现场体验放在第一位。",
      rationale: "把一个可有可无的希洛项目挪开，换成山顶日落或火山观景。",
      actions: ["确认官方是否开放", "带好保暖衣物和照明", "挪掉可选的希洛下午"],
    },
    negative: {
      branchId: "coast-first",
      title: "别再追天气，把时间留给海岸和北岸。",
      rationale: "魔鬼鱼、平静水域浮潜和北岸本身就很好玩，也不用为了天气来回折腾。",
      actions: ["确认魔鬼鱼活动照常", "选一个风浪较小的浮潜点", "退掉备用的火山村住宿"],
    },
  },
  branches: [
    {
      id: "weather-window",
      name: "留一个晚上看天气",
      subtitle: "只挪一个晚上，不重排整趟旅行",
      days: 7,
      cost: 3950,
      transportMode: "飞机 + 租车",
      transitHours: 18,
      driveHours: 18,
      luggageFlexibility: "Medium",
      bookingComplexity: "Medium",
      fatigue: 7,
      experienceScore: 9,
      flexibility: "High",
      outcomes: ["pending", "positive", "negative"],
      summary: "两边的住宿都不动，只让一个晚上跟着天气走。",
      changes: ["留一个晚上可以临时调整", "把天气最好的一晚留给冒纳凯阿或火山"],
      tradeoffs: ["有一晚不能提前排满", "可能要多开一段回头路"],
      timeline: [
        { day: "第 1–2 天", title: "科纳海岸", detail: "魔鬼鱼 + 风浪较小的浮潜点" },
        { day: "第 3–4 天", title: "火山村", detail: "逛公园，晚上根据天气机动" },
        { day: "第 5–7 天", title: "希洛和北岸", detail: "瀑布 + 沿北岸回科纳" },
      ],
    },
    {
      id: "live-event",
      name: "天气好就追现场",
      subtitle: "难得的体验优先，其他项目让路",
      days: 7,
      cost: 4100,
      transportMode: "飞机 + 租车",
      transitHours: 21,
      driveHours: 21,
      luggageFlexibility: "Medium",
      bookingComplexity: "High",
      fatigue: 8,
      experienceScore: 10,
      flexibility: "Medium",
      outcomes: ["positive"],
      summary: "官方条件合适时再回火山或上山顶，可选项目就先放弃。",
      changes: ["拿掉一个可选的希洛下午", "只有官方条件合适才多开这一趟"],
      tradeoffs: ["少看一个瀑布或市场", "多开 3 个小时"],
      timeline: [
        { day: "第 1–5 天", title: "主路线先不动", detail: "科纳 → 火山村 → 希洛" },
        { day: "第 6 天", title: "回去追现场", detail: "只有官方条件合适才出发" },
        { day: "第 7 天", title: "北岸回科纳", detail: "返程航班和沿途风景都保留" },
      ],
    },
    {
      id: "coast-first",
      name: "不追天气，慢慢玩海岸",
      subtitle: "天气不给力时最轻松",
      days: 7,
      cost: 3700,
      transportMode: "飞机 + 租车",
      transitHours: 15,
      driveHours: 15,
      luggageFlexibility: "Medium",
      bookingComplexity: "Low",
      fatigue: 5,
      experienceScore: 8,
      flexibility: "Medium",
      outcomes: ["pending", "negative"],
      summary: "不再为了天气来回跑，把省下来的时间留给海滩和北岸。",
      changes: ["不再二刷火山或山顶", "北岸多留一个慢慢玩的白天"],
      tradeoffs: ["看不到火山现场", "没有山顶日落"],
      timeline: [
        { day: "第 1–3 天", title: "科纳", detail: "魔鬼鱼 + 难度较低的水上活动" },
        { day: "第 4–5 天", title: "火山和希洛", detail: "白天逛公园，再看瀑布" },
        { day: "第 6–7 天", title: "北岸", detail: "威美亚 + 沿途海滩" },
      ],
    },
  ],
  checklist: [
    { id: "hawaii-1", label: "确认魔鬼鱼活动的取消规则", dueDate: "免费取消前", kind: "check", done: true },
    { id: "hawaii-2", label: "看公园通知和山顶天气", dueDate: "提前 48 小时", kind: "decide", done: false },
    { id: "hawaii-3", label: "退掉最后没用上的备用住宿", dueDate: "免费取消前", kind: "cancel", done: false },
  ],
  updatedAt: "2026-07-20T12:00:00.000Z",
};
